MOUSEKEY_ENABLE    = no    # Mouse keys
RGBLIGHT_ENABLE    = no    # Enable WS2812 RGB underlight.
OLED_ENABLE        = yes
OLED_DRIVER        = SSD1306
LTO_ENABLE         = yes
CAPS_WORD_ENABLE   = yes
BOOTMAGIC_ENABLE   = yes
VIA_ENABLE         = yes
COMMAND_ENABLE     = no
EXTRAFLAGS 			  += -flto
